<?php
/**
 * Title: Reasons Why and Contact
 * Slug: rivers-edge/reasons-why-and-contact
 * Categories: About
 */
?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Reasons Why and Contact"},"className":"is-style-reasons-why-and-contact","style":{"spacing":{"padding":{"right":"var:preset|spacing|50","left":"var:preset|spacing|50","bottom":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group is-style-reasons-why-and-contact" style="padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"padding":{"right":"var:preset|spacing|50","left":"var:preset|spacing|50","top":"var:preset|spacing|30","bottom":"var:preset|spacing|40"},"margin":{"top":"0","bottom":"0"}}},"backgroundColor":"accent-2","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group has-accent-2-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"style":{"spacing":{"padding":{"right":"var:preset|spacing|30","left":"var:preset|spacing|30","top":"0","bottom":"0"},"margin":{"top":"var:preset|spacing|40","left":"var:preset|spacing|20"}},"layout":{"selfStretch":"fill","flexSize":null}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="margin-top:var(--wp--preset--spacing--40);margin-left:var(--wp--preset--spacing--20);padding-top:0;padding-right:var(--wp--preset--spacing--30);padding-bottom:0;padding-left:var(--wp--preset--spacing--30)"> Contact for a Free Scan </h2>
<!-- /wp:heading -->

<!-- wp:kadence/form {"uniqueID":"464_d069ba-ca","postID":"464","style":[{"showRequired":true,"size":"standard","deskPadding":["","","",""],"tabletPadding":["","","",""],"mobilePadding":["","","",""],"color":"","requiredColor":"","background":"","border":"","backgroundOpacity":1,"borderOpacity":1,"borderRadius":"","borderWidth":["","","",""],"colorActive":"","backgroundActive":"","borderActive":"","backgroundActiveOpacity":1,"borderActiveOpacity":1,"gradient":["#999999",1,0,100,"linear",180,"center center"],"gradientActive":["#777777",1,0,100,"linear",180,"center center"],"backgroundType":"solid","backgroundActiveType":"solid","boxShadow":[false,"#000000",0.2,1,1,2,0,false],"boxShadowActive":[false,"#000000",0.4,2,2,3,0,false],"fontSize":["md","",""],"fontSizeType":"px","lineHeight":["","",""],"lineType":"px","rowGap":"","rowGapType":"px","gutter":"","gutterType":"px","tabletRowGap":"","mobileRowGap":"","tabletGutter":"","mobileGutter":""}],"labelFont":[{"color":"#FFFFFF","size":["","",""],"sizeType":"px","lineHeight":["","",""],"lineType":"px","letterSpacing":"","textTransform":"","family":"","google":"","style":"","weight":"","variant":"","subset":"","loadGoogle":true,"padding":["","","",""],"margin":["","","",""]}],"submit":[{"label":"\u003cstrong\u003eSubmit\u003c/strong\u003e","width":["100","",""],"size":"standard","widthType":"auto","fixedWidth":["","",""],"align":["","",""],"deskPadding":["","","",""],"tabletPadding":["","","",""],"mobilePadding":["","","",""],"color":"#0a3a42","background":"#a8e4e8","border":"","backgroundOpacity":1,"borderOpacity":1,"borderRadius":0,"borderWidth":["","","",""],"colorHover":"","backgroundHover":"","borderHover":"","backgroundHoverOpacity":1,"borderHoverOpacity":1,"icon":"","iconSide":"right","iconHover":false,"cssClass":"","gradient":["#999999",1,0,100,"linear",180,"center center"],"gradientHover":["#777777",1,0,100,"linear",180,"center center"],"btnStyle":"basic","btnSize":"standard","backgroundType":"solid","backgroundHoverType":"solid","boxShadow":[false,"#000000",0.2,1,1,2,0,false],"boxShadowHover":[false,"#000000",0.4,2,2,3,0,false]}]} -->
<div class="wp-block-kadence-form kadence-form-464_d069ba-ca kb-form-wrap"><form class="kb-form" action="" method="post"><div class="kadence-blocks-form-field kb-field-desk-width-100 kb-input-size-standard"><label for="kb_field_464_d069ba-ca_0">Name</label><input name="kb_field_0" id="kb_field_464_d069ba-ca_0" data-label="Name" type="text" placeholder="" value="" data-type="text" class="kb-field kb-text-style-field kb-text-field kb-field-0"/></div><div class="kadence-blocks-form-field kb-form-field-1 kb-field-desk-width-100 kb-input-size-standard"><label for="kb_field_464_d069ba-ca_1">Email<span class="required">*</span></label><input name="kb_field_1" id="kb_field_464_d069ba-ca_1" data-label="Email" type="email" placeholder="" value="" data-type="email" class="kb-field kb-text-style-field kb-email-field kb-field-1" data-required="yes"/></div><div class="kadence-blocks-form-field kb-form-field-2 kb-field-desk-width-100 kb-input-size-standard"><label for="kb_field_464_d069ba-ca_2">Message<span class="required">*</span></label><textarea name="kb_field_2" id="kb_field_464_d069ba-ca_2" data-label="Message" type="textarea" placeholder="" data-type="textarea" class="kb-field kb-text-style-field kb-textarea-field kb-field-2" rows="4" data-required="yes"></textarea></div><input type="hidden" name="_kb_form_id" value="464_d069ba-ca"/><input type="hidden" name="_kb_form_post_id" value="464"/><input type="hidden" name="action" value="kb_process_ajax_submit"/><input class="kadence-blocks-field verify" type="text" name="_kb_verify_email" autocomplete="off" aria-hidden="true" placeholder="Email" tabindex="-1"/><div class="kadence-blocks-form-field kb-submit-field kb-field-desk-width-100"><button class="kb-forms-submit button kb-button-size-standard kb-button-width-auto"><strong>Submit</strong></button></div></form></div>
<!-- /wp:kadence/form --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"right":"var:preset|spacing|40","left":"var:preset|spacing|40","top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"},"margin":{"top":"0","bottom":"0"}}},"backgroundColor":"base","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group has-base-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="http://192.168.1.17:8012/wp-content/uploads/2025/12/ada_infographic_horizontal.webp" alt="" class=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->